### PR TITLE
Add and use method to check true/false values

### PR DESCRIPTION
**Pull request by sandain**
Add and use method to check true/false values. Inspired by PR #271 from @Roflicide

### CODE REVIEW

**Comment by zanix** [comment]
Nice, now hopefully I can find time to test this

**Comment by Roflicide** [comment]
yes, i will  test this as well, thanks for the PR @sandain !

**Comment by sandain** [comment]
Has anyone had the chance to test this?  I'm not having any issues with it, but I don't have time to play this game any more, so I haven't fully tested this change. All I have time to check for is whether the server starts and whether I get a valid query back from the server, and both work just fine.

**Comment by zanix** [comment]
Not yet, haven't had time

**Comment by Roflicide** [comment]
just tested this and it works nicely!

**Review by zanix — APPROVED** [review]
Seems to work, ship it!

**Comment by sandain** [comment]
Thanks for testing @Roflicide and @zanix

**Pull request merged**
