### PR TITLE
Overviewer readme update

### PR DESCRIPTION
**Pull request by Roflicide**
Updated the docs to include instructions on setting up Overviewer; this includes much of the same README language as pull request [#160](https://github.com/MinecraftServerControl/mscs/pull/160) except: 

- it includes a link to a script in the README that the user can run in order to patch Overviewer
- I removed the wording on creating a mscs.defaults file if one wasn't already created, as [#166](https://github.com/MinecraftServerControl/mscs/pull/166) satisfies this 
- fixed some typos

### CODE REVIEW

**Comment by Roflicide** [comment]
@zanix I'm not sure if I incorporated all of your comments from the last pull request into this one; I apologize if I haven't--please update it as you see fit

**Comment by zanix** [comment]
@Roflicide ok, I will try to take a look this weekend.

**Comment by sandain** [comment]
This looks good. Thanks. I want to take a closer look at it again later this weekend though.

**Comment by zanix** [comment]
I think you got all my comments from the other PR. Hopefully I can review this PR entirely tomorrow.

**Comment by sandain** [comment]
I had a chance to look over this again, and I like the changes.  I'll wait for @Zanix to give comments before accepting this change.  It would be nice to get my pull request (#166) in first since the wording here assumes that it is already in.

**Comment by zanix** [comment]
Finally had a chance to review, I think it looks good. @sandain I agree with getting that other PR in first.

**Pull request merged**
